#!/bin/env bash

# dmenu script to quickly access config files

EDITOR="nvim"
#TERM="alacritty"

declare -a options=(
"alacritty - $HOME/.config/alacritty/alacritty.yml"
"bash - $HOME/.bashrc"
"dunst - $HOME/.config/dunst/dunstrc"
"dmenu - $HOME/.config/suckless/dmenu/config.def.h"
"dwm - $HOME/.config/suckless/dwm/config.def.h"
"dwmblocks - $HOME/.config/suckless/dwmblocks/blocks.def.h"
"leftwm - $HOME/.config/leftwm/config.toml"
"leftwm polybar - $HOME/.config/leftwm/themes/basic_polybar/polybar.config"
"leftwm themes - $HOME/.config/leftwm/themes/basic_polybar/theme.toml"
"neovim - $HOME/.config/nvim/init.vim"
"picom - $HOME/.config/picom/picom.conf"
"slstatus - $HOME/.config/suckless/slstatus/config.def.h"
"xinit - $HOME/.xinitrc"
"xmobar - $HOME/.xmobarrc"
"xmonad - $HOME/.xmonad/xmonad.hs"
"xprofile - $HOME/.xprofile"
"xresources - $HOME/.Xresources"
"quit"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -c -i -l 20)

if [[ "$choice" == "quit" ]]; then
        echo "Exiting..." && exit 1
elif [ "$choice" ]; then
        path=$(printf '%s\n' "${choice}" | awk '{printf $NF}')
        $EDITOR $path
else
        echo "User interrupt" && exit 1
fi
